version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.1"
    environment:
      DOMAIN: "https://tkimchaute.kintone.com"
      ADMIN_USERNAME: "tkimchaute"
      ADMIN_PASSWORD: "tkimchaute123"
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run: 
          name: Bootstrap Carthage
          command: scripts/bootstrap-if-needed.sh
      - save_cache:
          key: v1-dep-{{ checksum "Cartfile.resolved" }}
          paths:
            - vendor/bundle
            - Carthage
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE test_class:"GetAppTest"
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: testing_structure
